name: setenv
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: make install

      - name: Run migrations
        env:
          DBNAME: ${{ secrets.DBNAME }}
          DBUSER: ${{ secrets.DBUSER }}
          DBPASSWORD: ${{ secrets.DBPASSWORD }}
          DBHOST: ${{ secrets.DBHOST }}
          DBPORT: ${{ secrets.DBPORT }}
        run: make migrate

      - name: Run tests
        run: make test

      - name: Lint code
        run: make lint