name: setenv
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: make install

      - name: Debug environment
        run: |
          printenv
          python -c "import os; print('DATABASE_URL:', os.getenv('DATABASE_URL'))"

      - name: Run migrations
        env:
          DATABASE_URL: sqlite:///test.db
        run: |
          python manage.py check --database default
          python manage.py migrate --noinput

      - name: Run tests
        env:
          DATABASE_URL: sqlite:///test.db
        run: |
          python manage.py check --database default
          make test

      - name: Lint code
        run: make lint