name: setenv
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: make install

      - name: Run migrations (test DB)
        env:
          DATABASE_URL: sqlite:///test.db
        run: |
          make migrate
          python manage.py check --database default

      - name: Run tests
        env:
          DATABASE_URL: sqlite:///test.db
        run: make test

      - name: Lint code
        run: make lint