
name: setenv
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install UV
        run: pip install uv

      - name: Create virtual environment
        run: uv venv .venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          make install

      - name: Verify Django installation
        run: |
          source .venv/bin/activate
          python -c "import django; print(f'Django version: {django.__version__}')"

      - name: Run migrations (SQLite for CI)
        env:
          DATABASE_URL: "sqlite:///test.db"
        run: |
          source .venv/bin/activate
          make migrate

      - name: Run tests
        run: |
          source .venv/bin/activate
          make test

      - name: Run linting
        run: |
          source .venv/bin/activate
          make lint

      - name: Collect static files (optional)
        run: |
          source .venv/bin/activate
          make collectstatic
